// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import DatepickerController from "./datepicker_controller";
application.register("datepicker", DatepickerController);

import FlashController from "./flash_controller";
application.register("flash", FlashController);

import LikeController from "./like_controller";
application.register("like", LikeController);

import QrcodeController from "./qrcode_controller";
application.register("qrcode", QrcodeController);

import ProductsController from "./products_controller";
application.register("products", ProductsController);

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TimepickerController from "./timepicker_controller"
application.register("timepicker", TimepickerController)
